## Workflow

Dataset > Data preprocessing > Train|Test > SVM (support vector machine) > New data > Predcit

## Importing Dependencies

In [153]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

## Data Collection and analysis

In [154]:
# importing the dataset as pandas dataframe
diabetes_dataset = pd.read_csv("ML_Project2_Diabetes.csv")

In [155]:
# printing the 5 first row of our dataframe
diabetes_dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [156]:
# number of rows and columns
diabetes_dataset.shape

(768, 9)

In [157]:
# getting the statistical numbers of the data
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [158]:
# check the amount of data and repeatinig  0 -- non diabetic | 1 --  diabetic
diabetes_dataset["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

### 0 --> Non diabetic
### 1 --> diabetic

In [159]:
# group values based on 0, 1 and then getting the mean value of every column
diabetes_dataset.groupby(["Outcome"]).mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

## Separating data and labels

In [160]:
X = diabetes_dataset.drop(columns="Outcome", axis=1)
y = diabetes_dataset["Outcome"]

In [161]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [162]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

## Data Standarization

In [163]:
# If there is a difference in the values we need to standaranzie the data to make better predictions
# it basically transforms all data into 0 and 1 range

In [164]:
scaler = StandardScaler()

In [165]:
standardized_data = scaler.fit_transform(X)

In [166]:
standardized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [167]:
# assign the std values into X
X = standardized_data

In [168]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [169]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

## Train Tes split

In [170]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=2)

In [171]:
# check sizes of each train and test split
X.shape, X_train.shape, X_test.shape

((768, 8), (614, 8), (154, 8))

## Training the model

In [172]:
classifier = svm.SVC(kernel="linear")

In [173]:
# training the SVM Classifier
classifier.fit(X_train, y_train)

SVC(kernel='linear')

## Model Evaluation

In [174]:
# accuracy on train data
X_train_prediction = classifier.predict(X_train)
trainig_data_accuracy = accuracy_score(X_train_prediction,y_train)
print(f"Training data accuracy is {(trainig_data_accuracy * 100):.2f}%")

Training data accuracy is 78.66%


In [175]:
# accuracy on test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,y_test)
print(f"Training data accuracy is {(test_data_accuracy * 100):.2f}%")


Training data accuracy is 77.27%


## Making a Predictive System

In [176]:
input_data = ((11,143,94,33,146,36.6,0.254,51),(2,90,68,42,0,38.2,0.503,27))


In [177]:
# (ONLY IF YOU ARE PREDICTING ON ONE VALUE!)
# changing the input_data to a numpy array 
# input_data_as_numpy_array = np.asarray(input_data)

In [178]:
# (ONLY IF YOU ARE PREDICTING ON ONE VALUE!)
# reshape the array since we are predicting on one value
# input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

In [179]:
# input_data_reshaped

array([[ 11.   , 143.   ,  94.   ,  33.   , 146.   ,  36.6  ,   0.254,
         51.   ,   2.   ,  90.   ,  68.   ,  42.   ,   0.   ,  38.2  ,
          0.503,  27.   ]])

In [180]:
# standarize the input data
std_input_data = scaler.transform(input_data)

C:\Users\Javier\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [181]:
prediction = classifier.predict(std_input_data)

In [182]:
prediction

array([1, 0], dtype=int64)

In [183]:
for i in prediction:
    if i == 1:
        print("Patient has Diabetes")
    elif i == 0:
        print("Patient does not have Diabeted")
    else:
        print("Something went wrong!")

Patient has Diabetes
Patient does not have Diabeted
