In [1]:
# Array indexing

In [2]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# indexing on a 1D array [start:stop:step]

In [10]:
arr[8]

8

In [11]:
arr[1:5]

array([1, 2, 3, 4])

In [13]:
arr[:5]

array([0, 1, 2, 3, 4])

In [14]:
arr[::2] # step

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# replacing values

In [16]:
arr[:5] = 100

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr = np.arange(0,11)

In [19]:
slice_of_arr = arr[:6]

In [20]:
slice_of_arr[:] = 99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr  #changes in both arrays!!!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
# if you want a copy to avoid it! .copy()

In [24]:
arr_copy = arr.copy() 

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy[:] = 100

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_copy 

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [31]:
# Indexing 2D array

In [33]:
arr_2D = np.array([[5,10,15],[20,25,30],[34,40,45]])

In [34]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [34, 40, 45]])

In [35]:
# double bracket format (not ideal!)

In [37]:
arr_2D[0][0] # row column

5

In [38]:
arr_2D[0] #row

array([ 5, 10, 15])

In [39]:
arr_2D[1][1] # row column

25

In [40]:
arr_2D[2][1] # row  column

40

In [41]:
# comma single bracket notation

In [43]:
arr_2D[1,2]  # [row, column]

30

In [44]:
# submatrices of it

In [49]:
arr_2D[:2,1:] # slicing ronw, slicing column

array([[10, 15],
       [25, 30]])

In [56]:
arr_2D[1:,:2]

array([[20, 25],
       [34, 40]])

In [57]:
arr_2D[1:,1:]

array([[25, 30],
       [40, 45]])

In [58]:
# conditional seclection! (the most important)

In [59]:
arr = np.arange(1,11)

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
bool_arr = arr > 5 # bool values array

In [63]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
arr[bool_arr] # getting just the True value

array([ 6,  7,  8,  9, 10])

In [65]:
arr[arr > 5] # everything in just one step!

array([ 6,  7,  8,  9, 10])

In [67]:
arr[arr < 3] # grabbing all elements less than 3

array([1, 2])

In [ ]:
# Recap! indexing on 2D arrays!

In [68]:
arr_2D = np.arange(50).reshape(5,10)

In [69]:
arr_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [71]:
# grab 13,2, 23, 24

In [74]:
arr_2D[1:3,3:5]

array([[13, 14],
       [23, 24]])