In [89]:
# NumPy Arrays

In [90]:
import numpy as np

In [91]:
mylist = [1,2,3]

In [92]:
arr = np.array(mylist) # 1D array

In [93]:
arr

array([1, 2, 3])

In [94]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [95]:
np.array(my_mat)  # a 2D array list of lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
# Create range matrix. Similar to range but it returns arrays

In [97]:
np.arange(0,11,2) # start, stop ,step

array([ 0,  2,  4,  6,  8, 10])

In [98]:
#  0's array

In [99]:
np.zeros(3)

array([0., 0., 0.])

In [100]:
np.zeros((2,3)) # first item is row, second columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [101]:
# 1's array

In [102]:
np.ones(4)

array([1., 1., 1., 1.])

In [103]:
np.ones((3,4)) #2D array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [104]:
# linscape is like range but returns evenly spaced array

In [105]:
np.linspace(0,5,10) # start, stop, number of evenly spaced items 1D array

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [106]:
# eye matrix - 2D square matrix where 1 is diagonal

In [107]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [108]:
# random.rand

In [109]:
np.random.rand(5) # populates a 1D array with random numbers between 0 and 1

array([0.15871252, 0.11614221, 0.47668084, 0.25596337, 0.69701515])

In [110]:
np.random.rand(5,5) # a 3D array. no tuple needed this time!!

array([[6.30982806e-01, 1.60398387e-01, 6.71266005e-02, 9.80461304e-01,
        7.74535470e-02],
       [6.08850918e-02, 8.25631395e-01, 3.94039712e-04, 4.01864872e-01,
        9.07573094e-01],
       [2.73272080e-01, 2.62741658e-01, 9.45769707e-01, 4.16662375e-01,
        6.55920322e-01],
       [4.45875508e-01, 2.04952565e-01, 2.89831860e-01, 9.70660061e-01,
        2.36936239e-01],
       [7.29140952e-02, 2.19552244e-01, 3.82059151e-01, 9.30644449e-02,
        3.26453039e-01]])

In [111]:
# Gaussian distribution random numbers

In [112]:
np.random.randn(3)

array([-0.12264915, -0.06143874, -0.50789761])

In [113]:
np.random.randn(4,4) # a 2D array

array([[-0.02581903, -0.03120128,  0.9088755 ,  0.40454703],
       [ 0.02390803,  0.08893826, -1.19905471, -0.13093676],
       [ 0.58278147,  0.16977075, -0.06944699, -2.07132427],
       [-1.01239662, -0.34465556,  0.43951092, -0.46652593]])

In [114]:
# Random number

In [115]:
np.random.randint(1,100,10) # low and high number and number of elements

array([65,  8, 60, 80, 70, 97, 52, 87, 75, 22])

In [116]:
# Methods 

In [117]:
arr = np.arange(25)

In [118]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [119]:
ranarr = np.random.randint(0,50,10)

In [120]:
ranarr

array([ 2, 34, 24, 12, 11, 42, 28,  6, 32, 18])

In [121]:
# Reshape method

In [122]:
arr.reshape(5,5) # will reshape to the given values row col. it needs to be filled 5 x 5 =25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [123]:
# Max and min value  max() min()

In [124]:
ranarr.max()

42

In [125]:
ranarr.min()

2

In [126]:
# argmax() will return the index where the highest value is located

In [127]:
ranarr.argmax()

5

In [128]:
# argmin() will do the same with lowest value

In [129]:
ranarr.argmin()

0

In [130]:
# array shape 

In [131]:
arr.shape # 1D array

(25,)

In [132]:
arr = arr.reshape(5,5)

In [136]:
arr.shape # 2D array

(5, 5)

In [134]:
# Datatype of the array

In [137]:
arr.dtype

dtype('int32')